### ISSUE TITLE
A "zombie job" wich is in status RUNNING should be set to FAILED by the workhorse engine after an defined amount of time

### ISSUE THREAD

**Issue by mkuehle** [coodoo-io/workhorse#12]
A job execution wich is in status RUNNING but no worker is active or even the job-engine was down must be set to FAILED by Workhorse after an amount of time.
Otherwise theses zombie job exectuions stay in RUNNING until an user will cancel ist manually.

**Comment by laugen** [comment]
this is fixed with https://github.com/coodoo-io/workhorse/commit/b3166e50adf16048f4da7467fd2475bc21e9f564 / [version 1.3.0](https://search.maven.org/artifact/io.coodoo/workhorse/1.3.0/jar)

every 5 minutes there is a hunt for those zombies and if caught, they will be put directly to status ABORTED.

https://github.com/coodoo-io/workhorse/blob/d497dbaf181bfc5a1383aa48352bbae9bcfd6950/src/main/java/io/coodoo/workhorse/jobengine/control/JobQueuePoller.java#L44
